version: '3.9'

services:
  postgres:
    image: postgres:16.3
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=svalova
      - POSTGRES_PASSWORD=mydbpass
      - POSTGRES_DB=proxy
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
    tty: true

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres

  proxy:
    build: 
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - postgres